# def classify_text(text):
#     if len(text) % 2 == 0:
#         return "Original"
#     else:
#         return "Spun"

# use this to print the actual document being transformed into vectors+labeled
def classify_text(text):
    '''
    Tells the origin of a text portion
    :param text: it comes in a numpy.ndarray with one element, the actual label
    :return: class of the text
    '''
    print('Text content: ', text, type(text))
    if text == 'mg':
        text = 'This text is fabricated, it was generated by a machine!'
    elif text == 'og':
        text = 'This text is original, it was generated by a human!'
    else:
        text = 'Something went wrong, I do not know the origin of this text. Sorry.'
    return str(text)
